### ISSUE TITLE
Miscellaneous docs issues

### ISSUE THREAD

**Issue by object-Object** [FallingColors/HexMod#391]
- [x] Greater Teleport should more clearly explain that you will die if you give it absolute coordinates
    - Suggested wording:
      > The entity will be teleported along the given vector. Curiously, this vector seems to be an offset, not an absolute position in the world; if I use Vector Reflection +X as the vector, for example, the entity will end up precisely one block east of its original position. No matter the distance, it always seems to cost about ten Charged Amethyst.
- [x] The following logical operators still say `number`/`any` instead of `bool`: negation, equality, inequality, maximus, minimus, maximus II, minimus II
- [x] The link to Compass Purification in Hexing 101 doesn't work (#337)
- [x] The scrying lens foreshadowing should be removed, or else made more clear that the "way to have both" doesn't actually exist
- [x] Ceil/floor accepting vectors is undocumented
- [x] Greater Sentinel has no anchor (#305)
- [x] Multiplicative and Division Distillation still use "Dstl." in their full (non-book) translations
    https://github.com/gamma-delta/HexMod/blob/18cab3e0e3388f60af6118937c41aa7ce97a5380/Common/src/main/resources/assets/hexcasting/lang/en_us.json#L415-L416
- [x] Flight reference in Gravity Changer section should probably be removed or changed to reference Altiora
- [x] Altiora's arguments still say "entity, number, number"
- [x] Nullary Reflection's return type is "influence" but should probably be "null" to match all the other places where null is returned
- [x] The cost of break block is listed as "an eighth of one amethyst dust" while the cost of place block is listed as "a negligible amount of media"
- [x] Pehkui compat spell arguments should say "number" instead of "double"
- [x] Vector exalt/disint says top to bottom but should say bottom to top
- [x] #515 (Archer's Purification -> Archer's Distillation)
- [x] Quenching Allays: "thrice an Charged Amethyst Crystal"
- [x] #562 
- [x] Reading and Writing has a closing bracket without an opening bracket: https://hexcasting.hexxy.media/v/0.11.1-7/1.0/en_us/#patterns/readwrite

**Comment by Master-Bw3** [comment]
The Augur's Purification description states that "The number 0, Null, and the empty list become False; everything else becomes True." however, False also becomes False even though it isn't listed as one of the things that become False.

**Comment by Robotgiggle** [comment]
The intro page for the Great Spells section mentions that the great spell patterns are "sparsely recorded" but doesn't actually provide any indication of how to find the missing information. The only part of the book that explains what Ancient Scrolls are and how to find them is the page on Scrolls in the Items section, which is not something the average new player would think to look at when trying to find great spells.

**Comment by Robotgiggle** [comment]
The recipe for quenching an allay is cheaper than a default Flay Mind recipe - it only costs 10 dust rather than 100. However, this is completely undocumented, so there'd be no way for a player to actually know that unless they look in the code.

**Comment by walksanatora** [comment]
The cycle casting/iota storage varient spell is undocumented

**Comment by macks2008** [comment]
@Robotgiggle I discovered the same thing yesterday thanks to talia and created an issue for last night, #617 
This should probably be added to the list.

**Comment by object-Object** [comment]
Please open a new issue - also, can you confirm what exactly you named the cube?

**Comment by macks2008** [comment]
new issue opened #640 (Sorry for the delay. I meant to make the new issue BEFORE posting here)
I tried it both with "Debug Patterns" and "DEBUG PATTERNS". In both cases it made the cube glow as expected, but did not actually debug any patterns.
